### ISSUE TITLE
aqara cube side numbering from 1-6 instead of 0-5

### ISSUE THREAD

**Issue by mvharlan** [golles/Home-Assistant-Blueprints#1]
The aqara cube uses 1-6 to number it's sides. The blueprint uses 0-5. Is this intended, or should it be fixed?

**Comment by golles** [comment]
I don't think it should be 1-6, I've just tested my cube, sensor `sensor.NAME_cube_side` which only gives me numbers 0-5:

<img width="807" src="https://github.com/user-attachments/assets/0511ebfd-e5a8-4bcd-b41d-ec93e74b150d">

My cube is `MFKZQ01LM`: https://www.zigbee2mqtt.io/devices/MFKZQ01LM.html#side-numeric The documentation on this page is also confusing as it mentions from 0-6... which may indicate there are different models around?

By the way, the blueprints in this repo haven't been updated for several years and I'm no longer maintaining them here, you can find the latest versions in my config repo: https://github.com/golles/Home-Assistant-Config?tab=readme-ov-file#blueprints

**Comment by mvharlan** [comment]
My Model is Xiaomi MFKZQ01LM. It uses 1-6.... I  have modified the blueprint now for my setup. Maybe it would be wise to have chance to choose which range you prefer.

![Screenshot from 2024-10-23 10-58-43](https://github.com/user-attachments/assets/300623ae-f096-479a-b64f-42bb250f046f)

**Comment by golles** [comment]
It is interesting that our cubes seem to behave differently, copying the blueprint locally and making adjustments would be indeed the best for you to do.
